7 post comments
elifalinli/backend-nc-project pull request #10
Opened 2023-03-30 15:21 UTC by elifalinli

2023-03-30 15:29 UTC, NRMSMITH requested changes
your code is excellent -just a couple more tests to implement - see my comments. Please send another pr when done :)

2023-03-30 15:29 UTC, NRMSMITH commented on app.test.js
> +    return request(app)
you need to send something on this as well to prove that it's definitely testing the path

2023-03-30 15:29 UTC, NRMSMITH commented on app.test.js
> +  });
A couple more tests to add: 
201 or 400 (up to you): ignores unnecessary properties on the sent comment
404: non existent id
400: missing required keys

2023-03-31 08:22 UTC, popatre requested changes
Good stuff!
Just need to change one of the tests to be a 404 username not found, instead of 400

2023-03-31 08:22 UTC, popatre commented on app.test.js
> +      .expect(400)
This should be a 404 - username not found, please.

2023-03-31 08:22 UTC, popatre commented on app.test.js
> +      });
Looks good on the tests - just need to change the username one to be a 404

2023-03-31 08:22 UTC, popatre commented on controllers/error-handling.controllers.js
> +    res.status(400).send({ msg: "something is wrong with your request!" });
Im guessing you'll just have to change this one to a 404 - username not found to get the test to pass.

2023-03-31 08:22 UTC, popatre commented on controllers/games.controllers.js
> +    next(err);
Lovely stuff

2023-03-31 09:41 UTC, popatre approved these changes

2023-03-31 09:41 UTC, popatre commented on controllers/games.controllers.js
> +    console.log(err)
just a console log to remove

2023-03-31 09:53 UTC, merged