3 get api categories
elifalinli/backend-nc-project pull request #5
Opened 2023-03-27 15:13 UTC by elifalinli

please see the most recent code!

2023-03-27 15:29 UTC, NRMSMITH requested changes
Nearly there Elif! Please test for a 404 bad pathway too :)

-> Please do not 'close' this pull request, instead do your changes locally, then add, commit and push to this branch and then your pull request will update!! Just make sure you send it again through /nchelp pr tomorrow after the lecture! :)

2023-03-27 15:29 UTC, NRMSMITH commented on app.js
> +});
much cleaner 👍

2023-03-27 15:29 UTC, NRMSMITH commented on app.test.js
> +  });
Please test for a bad pathway! :)

2023-03-28 09:43 UTC, itskatherine approved these changes
Looks good Elif just get rid of those pesky console logs then good to merge! 👍

2023-03-28 09:43 UTC, itskatherine commented on app.test.js
> +        console.log(body)
Remember to get rid of console.logs for PRs 👀

2023-03-28 09:48 UTC, merged