resolve 6?
elifalinli/backend-nc-project pull request #9
Opened 2023-03-29 11:12 UTC by elifalinli

2023-03-29 11:36 UTC, NRMSMITH requested changes
just a couple of changes to tests!

2023-03-29 11:36 UTC, NRMSMITH commented on app.test.js
> +  });
if the review is real it should send back an empty array if no comments, so should be a 404

the 404 should be for a non-existant id :)

2023-03-30 09:54 UTC, popatre requested changes
Sorry - one more from me. 

You;ve got nested .thens - possibly caused by a .then where it isnt needed. Could you unnest them for me?

2023-03-30 09:54 UTC, popatre commented on models/games.models.js
> +    })
This doesnt need to be returned, as reviewRowCount is not asynchronous - you're not waiting on anything here

2023-03-30 09:54 UTC, popatre commented on models/games.models.js
> +      });
This could be moved to the .then block above - at the moment, you've got nested .thens here which will potentially mess up your single .then chain.

2023-03-30 10:23 UTC, Harrison365 commented
Hi Semra :) 

This looks good to go ✅ 
Just one thing, please could you add a length check before your forEach, this will avoid false positives.

No need for another pull request. Once this is fixed, you are good to merge 👍

2023-03-30 10:25 UTC, merged